import"./assets/styles-C95asHrQ.js";import{a as _,i as L}from"./assets/vendor-sGTqnghy.js";const S="https://dummyjson.com",y={CATEGORIES:"/products/category-list",PRODUCTS:"/products",CATEGORY_LIST:"/products/category/",PRODUCT_BY_ID:"/products/"},a=12;_.defaults.baseURL=S;async function B(){const{data:t}=await _(`${y.CATEGORIES}`);return t}async function b(t){const o=(t-1)*a,{data:r}=await _(`${y.PRODUCTS}?limit=${a}&skip=${o}`);return r}async function k(t,o){const r=(o-1)*a,{data:e}=await _(`${y.CATEGORY_LIST}${t}?limit=${a}&skip=${r}`);return e}async function M(t){const{data:o}=await _(`${y.PRODUCT_BY_ID}${t}`);return o}const s={categories:document.querySelector(".categories"),products:document.querySelector(".products"),modal:document.querySelector(".modal"),modalProduct:document.querySelector(".modal-product"),loadMoreBtn:document.querySelector(".load-more-btn"),notFound:document.querySelector(".not-found"),loader:document.querySelector(".loader")};function A(t){const r=["All",...t].map(e=>`<li class="categories__item">
   <button class="categories__btn" type="button">${e}</button>
 </li>
`).join("");s.categories.innerHTML=r}function p(t){const o=t.map(({id:r,category:e,brand:c,price:n,title:l,thumbnail:h})=>`
  <li class="products__item" data-id="${r}">
    <img class="products__image" src="${h}" alt="${l}"/>
    <p class="products__title">${l}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${c}</span></p>
    <p class="products__category">Category: ${e}</p>
    <p class="products__price">Price: ${n}$</p>
 </li>

  `).join("");s.products.insertAdjacentHTML("beforeend",o)}function R(){s.products.innerHTML=""}function I({price:t,title:o,thumbnail:r,tags:e,description:c,shippingInformation:n,returnPolicy:l}){const h=e.map(P=>`<li class="modal-product__tags">${P}</li>`).join(""),C=`<img class="modal-product__img" src="${r}" alt="${o}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${o}</p>
        <ul class="modal-product__tags">${h}</ul>
        <p class="modal-product__description">${c}</p>
        <p class="modal-product__shipping-information">Shipping: ${n}</p>
        <p class="modal-product__return-policy">Return Policy: ${l}</p>
        <p class="modal-product__price">Price: ${t}$</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>
`;s.modalProduct.innerHTML=C}function O(){s.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",E),s.modal.addEventListener("click",T)}function w(){s.modal.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",E),s.modal.removeEventListener("click",T)}function E(t){t.code==="Escape"&&w()}function T(t){t.target===s.modal&&w()}L.settings({timeout:5e3,balloon:!0,progressBar:!1});function f(t){L.info({message:`${t}`})}function g(t){L.error({title:"Ooops!",message:`${t.message}`})}function m(){setTimeout(()=>{s.loadMoreBtn.classList.remove("is-hidden")},500)}function i(){s.loadMoreBtn.classList.add("is-hidden")}function $(){s.loader.style.display="block",i()}function v(){s.loader.style.display="none"}let d=1,u="";async function D(){try{const t=await B();A(t),u="All",s.categories.children[0].children[0].classList.add("categories__btn--active"),$();const{products:r,total:e,limit:c,skip:n}=await b(d);p(r),m()}catch(t){g(t)}finally{v()}}async function q(t){const o=t.target.closest(".categories__btn");if(!o)return;[...t.currentTarget.children].map(e=>{e.children[0].classList.remove("categories__btn--active")}),R(),o.classList.add("categories__btn--active"),d=1,u=o.textContent,$();try{if(u==="All"){const{products:e,total:c,limit:n,skip:l}=await b(d);if(!e.length){s.notFound.classList.add("not-found--visible"),i();return}n<a?(i(),f("We're sorry, but you've reached the end of search results.")):m(),p(e)}else{const{products:e,total:c,limit:n,skip:l}=await k(u,d);if(!e.length){s.notFound.classList.add("not-found--visible"),i();return}n<a?(i(),f("We're sorry, but you've reached the end of search results.")):m(),p(e)}}catch(e){g(e)}finally{v()}}async function U(t){t.preventDefault(),d++,$();try{if(u=="All"){const{products:o,total:r,limit:e,skip:c}=await b(d);e<a?(i(),f("We're sorry, but you've reached the end of search results.")):m(),p(o)}else{const{products:o,total:r,limit:e,skip:c}=await k(u,d);e<a?(i(),f("We're sorry, but you've reached the end of search results.")):m(),p(o)}}catch(o){g(o)}finally{v()}}async function j(t){const o=t.target.closest(".products__item");if(!o)return;const r=Number(o.dataset.id);try{const e=await M(r);I(e),O()}catch(e){g(e)}}document.addEventListener("DOMContentLoaded",D);s.categories.addEventListener("click",q);s.products.addEventListener("click",j);s.loadMoreBtn.addEventListener("click",U);
//# sourceMappingURL=index.js.map
